language: node_js

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy .
  - docker tag reverseproxy arjunvreddy/reverseproxy:latest
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed arjunvreddy/udagram-api-feed:latest
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user arjunvreddy/udagram-api-user:latest
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend arjunvreddy/udagram-frontend:latest
  

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push arjunvreddy/reverseproxy
  - docker push arjunvreddy/udagram-api-feed
  - docker push arjunvreddy/udagram-api-user
  - docker push arjunvreddy/udagram-frontend

