# This file is used for convenience of local development.
# DO NOT STORE YOUR CREDENTIALS INTO GIT
export POSTGRES_USERNAME=POSTGRES_USERNAME
export POSTGRES_PASSWORD=POSTGRES_PASSWORD
export POSTGRES_HOST=POSTGRES_HOST_AWS
export POSTGRES_DB=POSTGRES_DB_NAME
export AWS_BUCKET=AWS_S3_BUCKET_NAME
export AWS_REGION=us-east-1
export AWS_PROFILE=default
export JWT_SECRET=JWT_SECRET
export URL=http://localhost:8100
